# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache {C:/Users/R ramadevi/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-13788-LAPTOP-D22V39SO/incrSyn}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/R ramadevi/OneDrive/Desktop/16_bit_RISC_Processer/16bir_RISC_Processer/16bir_RISC_Processer.cache/wt} [current_project]
set_property parent.project_path {C:/Users/R ramadevi/OneDrive/Desktop/16_bit_RISC_Processer/16bir_RISC_Processer/16bir_RISC_Processer.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/R ramadevi/OneDrive/Desktop/16_bit_RISC_Processer/16bir_RISC_Processer/16bir_RISC_Processer.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/R ramadevi/OneDrive/Desktop/16_bit_RISC_Processer/rtl/alu.sv}
  {C:/Users/R ramadevi/OneDrive/Desktop/16_bit_RISC_Processer/rtl/control_unit.sv}
  {C:/Users/R ramadevi/OneDrive/Desktop/16_bit_RISC_Processer/rtl/data_memory.sv}
  {C:/Users/R ramadevi/OneDrive/Desktop/16_bit_RISC_Processer/rtl/immediate_generator.sv}
  {C:/Users/R ramadevi/OneDrive/Desktop/16_bit_RISC_Processer/rtl/instruction_memory.sv}
  {C:/Users/R ramadevi/OneDrive/Desktop/16_bit_RISC_Processer/rtl/mux.sv}
  {C:/Users/R ramadevi/OneDrive/Desktop/16_bit_RISC_Processer/rtl/program_counter.sv}
  {C:/Users/R ramadevi/OneDrive/Desktop/16_bit_RISC_Processer/rtl/register_file.sv}
  {C:/Users/R ramadevi/OneDrive/Desktop/16_bit_RISC_Processer/rtl/cpu_top.sv}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/R ramadevi/OneDrive/Desktop/16_bit_RISC_Processer/16bir_RISC_Processer/16bir_RISC_Processer.srcs/constrs_1/new/timing_constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/R ramadevi/OneDrive/Desktop/16_bit_RISC_Processer/16bir_RISC_Processer/16bir_RISC_Processer.srcs/constrs_1/new/timing_constraints.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top cpu_top -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cpu_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cpu_top_utilization_synth.rpt -pb cpu_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
